import type { NextPage } from "next"
import Head from "next/head"
// import Image from "next/image"

const Home: NextPage = () => (
  <div className="">
    <Head>
      <title>evans</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div>nandwa</div>
  </div>
)

export default Home
