import type { NextPage } from "next"
import Head from "next/head"
import Header from "@evans/components/Navigation/Header"
// import Image from "next/image"

const Home: NextPage = () => (
  <div className="min-h-screen bg-gray-300">
    <Head>
      <title>evans</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header/>
  </div>
)

export default Home
